# Generated by Django 5.0.7 on 2024-07-19 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SparrowApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorydb',
            old_name='name',
            new_name='company',
        ),
    ]
