# Generated by Django 5.0.7 on 2024-07-19 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SparrowApp', '0002_rename_name_categorydb_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorydb',
            old_name='company',
            new_name='item',
        ),
    ]
